
export const THERAPY_CATEGORYES = [
    { value: "Active Release Therapy", label: "Active Release Therapy" },
    { value: "Acupuncture", label: "Acupuncture" },
    { value: "Athlete Performance Diet", label: "Athlete Performance Diet" },
    { value: "Bodybuilding Nutrition", label: "Bodybuilding / Muscle Gain Nutrition" },
    { value: "Balanced Diet", label: "Balanced Diet Planning" },
    { value: "Cardiac Diet", label: "Cardiac Diet Planning (Heart Health)" },
    { value: "Cancer Nutrition", label: "Cancer Nutrition" },
    { value: "Child Nutrition", label: "Child Nutrition" },
    { value: "Diabetic Diet", label: "Diabetic Diet Planning" },
    { value: "Dry Cupping", label: "Dry Cupping (Spot, Movement, Fire)" },
    { value: "Dry Needling", label: "Dry Needling/Trigger Point Therapy" },
    { value: "Electrotherapy", label: "Electrotherapy (TENS, Ultrasound)" },
    { value: "Endurance Diet", label: "Endurance & Recovery Diet" },
    { value: "Elderly Care", label: "Elderly Care/Geriatric Therapy" },
    { value: "Foot & Reflexology Massage", label: "Foot & Reflexology Massage" },
    { value: "Gastrointestinal Diet", label: "Gastrointestinal Diet (IBS, Acidity, Digestion)" },
    { value: "Geriatric Nutrition", label: "Geriatric Nutrition (Elderly)" },
    { value: "Head/Neck/Shoulder Massage", label: "Head/Neck/Shoulder Massage" },
    { value: "Hot Stone Massage", label: "Hot Stone Massage" },
    { value: "Immunity Diet", label: "Immunity-Boosting Diets" },
    { value: "IASTM", label: "IASTM (Instrument Assisted Soft Tissue Mobilization)" },
    { value: "Meditation Therapy", label: "Meditation & Mindfulness Therapy" },
    { value: "Myofascial Release", label: "Myofascial Release" },
    { value: "Neurological Therapy", label: "Neurological Therapy (Stroke, Paralysis, Parkinson's)" },
    { value: "Orthopedic Therapy", label: "Orthopedic Therapy (Fracture, Joint Issues)" },
    { value: "PCOS Diet", label: "PCOS/PCOD Diet Plans" },
    { value: "Pediatric Nutrition", label: "Pediatric Nutrition (child-specific)" },
    { value: "Post-Surgery Rehabilitation", label: "Post-Surgery Rehabilitation" },
    { value: "Posture Correction", label: "Posture Correction" },
    { value: "Pregnancy Nutrition", label: "Pregnancy & Lactation Nutrition" },
    { value: "Renal Diet", label: "Renal Diet (Kidney Patients)" },
    { value: "Skin Hair Diet", label: "Skin & Hair Nutrition" },
    { value: "Sleep Therapy", label: "Sleep Therapy" },
    { value: "Sports Therapy", label: "Sports Therapy (Injury Recovery, Muscle Strain)" },
    { value: "Stress Diet", label: "Stress & Anxiety Food Plans" },
    { value: "Stress Management Therapy", label: "Stress Management Therapy" },
    { value: "Swedish Massage", label: "Swedish Massage (Relaxation)" },
    { value: "Thai Massage", label: "Thai Massage (Stretch-based)" },
    { value: "Weight Loss", label: "Weight Loss/Gain Diets" },
    { value: "Weight Management Therapy", label: "Weight Management Therapy" },
    { value: "Wet Cupping", label: "Wet Cupping (Hijama, Detoxification)" },
    { value: "Women's Health", label: "Women's Health (Pre/Postnatal Therapy, PCOS Care)" },
    { value: "Yoga Therapy", label: "Yoga Therapy" }
];